query ads($limit:Int,$offset:Int){
  ads(order_by:{pos:asc},limit:$limit,offset:$offset){
    id
    action_url
    duration
    description
    title
    img
    action_text
    type
    log
  }
  ads_aggregate{
    aggregate{
      count
    }
  }
}